services:

  source-code:
    volumes:
      - ./../source:/var/www/html
      - ./php/uploads:/uploads

  php:
    image: php:8.1.13-fpm-alpine3.17
    extends:
      service: source-code
    user: "${UID:?err}:${GID:?err}"
    env_file: ./php/.env.localhost
    depends_on:
      - mariadb
      - redis
    networks:
      - default
      - egress
